### ISSUE TITLE
GCC and clang can detect popcount_mult and optimize it to popcnt

### ISSUE THREAD

**Issue by camel-cdr** [BartMassey/popcount#1]
Addressing the question posed in the README

>Interestingly, the multiply-based popcount benches as fast as the POPCNT instruction on this hardware! I have a hard time believing this — explanations welcome.

I found that GCC and clang can detect the implementation of popcount_mult and optimize it to a single `popcnt` instruction which is why it's as fast as `__builtin_popcount`, see https://godbolt.org/z/KM68aE995.

If you want to mitigate this optimization you can insert `__asm__("":"+r"(x));` between somewhere into the implementation of `popcount_mult`, which should stop the compiler from detecting it, see https://godbolt.org/z/xb5hKsbWo.

**Comment by BartMassey** [comment]
LOL. Never occurred to me to check, which is a failure on my part. Thanks very much!

I'll poke at it and push a fix as soon as possible.

*Edit:* Looking at the README, it had occurred to me in March when this problem first appeared that it might be this. I should have investigated further then. I just couldn't believe it — still barely can.

**Comment by BartMassey** [comment]
Heh. The fix for C was OK — the fix for Rust was harder and isn't great. Thanks again!

**Comment by camel-cdr** [comment]
I looked at this again today and it looks like clang actually makes the code worse on some platforms (riscv): https://godbolt.org/z/nPsP38MPr

**Comment by BartMassey** [comment]
Sigh. Looks like Clang is actually using `popcount_mult` as its builtin popcount (terrible idea), and that both compilers are reading through both of our hacks for trying to stop the pattern match on RiscV: I guess the pattern matcher is more robust? That's gross. I wonder if there's some way we can enforce not doing this super-frustrating pattern match?
